---
title: "Plotting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{plotting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Example of some plotting possibilities

```{r setup}
rm(list=ls())

# devtools::install_github("marzuf/MANUSCRIPT_FIGURES", subdir="COCODATA")
# 
# if(!require(COCODATA))
#   devtools::install_github("marzuf/MANUSCRIPT_FIGURES", subdir="COCODATA")
  # alternatively: 
  # install.packages("COCODATA_0.0.0.1.tar.gz", repos = NULL, type ="source")
 # data("norm_ID")
library(COCODATA)
```



### Conserved region

``` {r plot_conserved, fig.height=8, fig.width=14}
data("conserved_region_130_genes_plot_dt") # this loads genes_plot_dt
head(genes_plot_dt)

data("conserved_region_130_tads_plot_dt") # this loads tads_plot_dt
head(tads_plot_dt)

plot_conservedRegions(genes_dt=genes_plot_dt, 
                      tads_dt=tads_plot_dt,
                      dsCat_cols = setNames(c("firebrick3", "navy", "gray50"), c("wt_vs_mut", "norm_vs_tumor", "subtypes")))
```

### Volcano-like intra-TAD corr. vs. TAD meanLogFC

NB: see the <em>tad_level_stats</em> vignette for computing TAD meanLogFC and mean intra-correlation.

``` {r plot_volcano, fig.height=6, fig.width=8}
data("ENCSR489OCU_NCI-H460_40kb_TCGAluad_norm_luad_all_meanCorr_TAD") # this loads all_meanCorr_TAD
data("ENCSR489OCU_NCI-H460_40kb_TCGAluad_norm_luad_all_meanLogFC_TAD") # this loads all_meanLogFC_TAD
data("ENCSR489OCU_NCI-H460_40kb_TCGAluad_norm_luad_emp_pval_combined") # this loads emp_pval_combined

plot_volcanoTADsCorrFC(meanCorr=all_meanCorr_TAD, 
                       meanFC=all_meanLogFC_TAD, 
                       comb_pval=emp_pval_combined,
                       tads_to_annot = "chr11_TAD390")
```



##### FCC cumsum curves

see the <em>tad_level_stats</em> vignette !

